-- MySQL Script generated by MySQL Workbench
-- Tue Mar  5 11:55:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Yotube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Yotube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Yotube` DEFAULT CHARACTER SET utf8 ;
USE `Yotube` ;

-- -----------------------------------------------------
-- Table `Yotube`.`Canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yotube`.`Canal` (
  `canal_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `creado_por_usuario_id` INT NOT NULL,
  PRIMARY KEY (`canal_id`),
  UNIQUE INDEX `canal_id_UNIQUE` (`canal_id` ASC) VISIBLE,
  UNIQUE INDEX `creado_por_usuario_id_UNIQUE` (`creado_por_usuario_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Yotube`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yotube`.`Usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `genero` ENUM('Hombre', 'Mujer') NOT NULL,
  `codgio_postal` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Yotube`.`Canal_Sub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yotube`.`Canal_Sub` (
  `u_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `c_canal_id` INT NOT NULL,
  PRIMARY KEY (`u_usuario_id`),
  UNIQUE INDEX `c_canal_id_UNIQUE` (`c_canal_id` ASC) VISIBLE,
  UNIQUE INDEX `u_usuario_id_UNIQUE` (`u_usuario_id` ASC) VISIBLE,
  CONSTRAINT `1`
    FOREIGN KEY (`c_canal_id`)
    REFERENCES `Yotube`.`Canal` (`canal_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `2`
    FOREIGN KEY (`u_usuario_id`)
    REFERENCES `Yotube`.`Usuario` (`usuario_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Yotube`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yotube`.`Comentario` (
  `comentario_id` INT NOT NULL AUTO_INCREMENT,
  `texto_comentario` VARCHAR(300) NULL DEFAULT NULL,
  `fecha_comentario` DATETIME NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`comentario_id`),
  UNIQUE INDEX `comentario_id_UNIQUE` (`comentario_id` ASC) VISIBLE,
  INDEX `usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Yotube`.`Usuario` (`usuario_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Yotube`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yotube`.`Video` (
  `video_id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `tamanyo` BLOB NULL DEFAULT NULL,
  `nombre_archivo` VARCHAR(45) NOT NULL,
  `duracion` VARCHAR(45) NULL DEFAULT NULL,
  `thumbnail` BLOB NOT NULL,
  `num_reproducciones` INT NULL DEFAULT NULL,
  `num_likes` INT NULL DEFAULT NULL,
  `num_dislikes` INT NULL DEFAULT NULL,
  `estado` ENUM('Public', 'Oculto', 'Privado') NOT NULL,
  `fecha_hora_publicacion` DATETIME NOT NULL,
  `publicado_por_usuario_id` INT NOT NULL,
  PRIMARY KEY (`video_id`),
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC) VISIBLE,
  UNIQUE INDEX `video_id_UNIQUE` (`video_id` ASC) VISIBLE,
  INDEX `usuario_idx` (`publicado_por_usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuarioo`
    FOREIGN KEY (`publicado_por_usuario_id`)
    REFERENCES `Yotube`.`Usuario` (`usuario_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Yotube`.`Etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yotube`.`Etiqueta` (
  `etiqueta_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`etiqueta_id`),
  UNIQUE INDEX `etiqueta_id_UNIQUE` (`etiqueta_id` ASC) VISIBLE,
  UNIQUE INDEX `video_id_UNIQUE` (`video_id` ASC) VISIBLE,
  CONSTRAINT `videoo`
    FOREIGN KEY (`video_id`)
    REFERENCES `Yotube`.`Video` (`video_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Yotube`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yotube`.`Playlist` (
  `playlist_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `estado` ENUM('Publico', 'Oculto', 'Privado') NULL DEFAULT NULL,
  `creado_por_usuario_id` INT NOT NULL,
  `video_add_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`playlist_id`),
  UNIQUE INDEX `playlist_id_UNIQUE` (`playlist_id` ASC) VISIBLE,
  INDEX `usuario_idx` (`creado_por_usuario_id` ASC) VISIBLE,
  INDEX `video_idx` (`video_add_id` ASC) VISIBLE,
  CONSTRAINT `ussuario`
    FOREIGN KEY (`creado_por_usuario_id`)
    REFERENCES `Yotube`.`Usuario` (`usuario_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `video`
    FOREIGN KEY (`video_add_id`)
    REFERENCES `Yotube`.`Video` (`video_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Yotube`.`Puntuacion_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yotube`.`Puntuacion_comentario` (
  `puntuado_por_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `c_comentario_id` INT NOT NULL,
  `fecha_hora_comentario` DATETIME NOT NULL,
  `like` INT NULL DEFAULT NULL,
  `dislike` INT NULL DEFAULT NULL,
  PRIMARY KEY (`puntuado_por_usuario_id`),
  UNIQUE INDEX `c_comentario_id_UNIQUE` (`c_comentario_id` ASC) VISIBLE,
  CONSTRAINT `comentario`
    FOREIGN KEY (`c_comentario_id`)
    REFERENCES `Yotube`.`Comentario` (`comentario_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `user`
    FOREIGN KEY (`puntuado_por_usuario_id`)
    REFERENCES `Yotube`.`Usuario` (`usuario_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Yotube`.`Puntuacion_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yotube`.`Puntuacion_video` (
  `u_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `v_video_id` INT NOT NULL,
  `fecha_like_dislike` DATETIME NULL DEFAULT NULL,
  `like` INT NULL DEFAULT NULL,
  `dislike` INT NULL DEFAULT NULL,
  PRIMARY KEY (`u_usuario_id`),
  UNIQUE INDEX `u_usuario_id_UNIQUE` (`u_usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `v_video_id_UNIQUE` (`v_video_id` ASC) VISIBLE,
  CONSTRAINT `video_`
    FOREIGN KEY (`v_video_id`)
    REFERENCES `Yotube`.`Video` (`video_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
