-- MySQL Script generated by MySQL Workbench
-- Tue Mar  5 18:07:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotify` DEFAULT CHARACTER SET utf8 ;
USE `Spotify` ;

-- -----------------------------------------------------
-- Table `Spotify`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `cumpleanyos` DATE NULL,
  `genero` ENUM("Hombre", "Mujer") NULL COMMENT '			',
  `pais` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `tipo_usuario` ENUM("Free", "Premium") NULL,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`usuario_premium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`usuario_premium` (
  `sub_id` INT NOT NULL AUTO_INCREMENT,
  `start_sub` DATETIME NOT NULL,
  `renovacion_sub` DATETIME NOT NULL,
  `metodo_pago` ENUM("Tarjeta", "Paypal") NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`sub_id`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `sub_id_UNIQUE` (`sub_id` ASC) VISIBLE,
  CONSTRAINT `usuario_usu`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Spotify`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`playlist` (
  `playlist_id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `total_canciones` INT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_eliminada` DATETIME NULL,
  `creada_por_id` INT NOT NULL,
  PRIMARY KEY (`playlist_id`),
  UNIQUE INDEX `playlist_id_UNIQUE` (`playlist_id` ASC) VISIBLE,
  INDEX `playlist_u_idx` (`creada_por_id` ASC) VISIBLE,
  CONSTRAINT `playlist_u`
    FOREIGN KEY (`creada_por_id`)
    REFERENCES `Spotify`.`usuario` (`usuario_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`artitsta_favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`artitsta_favorito` (
  `u_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `a_artista_id` INT NOT NULL,
  PRIMARY KEY (`u_usuario_id`),
  UNIQUE INDEX `u_usuario_id_UNIQUE` (`u_usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `a_artista_id_UNIQUE` (`a_artista_id` ASC) VISIBLE,
  CONSTRAINT `fav_user`
    FOREIGN KEY (`u_usuario_id`)
    REFERENCES `Spotify`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`artista` (
  `artista_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `foto` BLOB NULL,
  PRIMARY KEY (`artista_id`),
  UNIQUE INDEX `artista_id_UNIQUE` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `fav_artista`
    FOREIGN KEY (`artista_id`)
    REFERENCES `Spotify`.`artitsta_favorito` (`a_artista_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`album` (
  `album_id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `year_publicado` DATETIME NOT NULL,
  `portada` BLOB NULL,
  `fk_artista` INT NOT NULL,
  PRIMARY KEY (`album_id`),
  INDEX `a_artista_idx` (`fk_artista` ASC) VISIBLE,
  CONSTRAINT `a_artista`
    FOREIGN KEY (`fk_artista`)
    REFERENCES `Spotify`.`artista` (`artista_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`cancion` (
  `cancion_id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `duracion` VARCHAR(45) NULL,
  `num_reproducciones` INT NULL,
  `fk_album_id` INT NOT NULL,
  PRIMARY KEY (`cancion_id`),
  UNIQUE INDEX `cancion_id_UNIQUE` (`cancion_id` ASC) VISIBLE,
  INDEX `album_idx` (`fk_album_id` ASC) VISIBLE,
  CONSTRAINT `album`
    FOREIGN KEY (`fk_album_id`)
    REFERENCES `Spotify`.`album` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`add_cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`add_cancion` (
  `add_cancion_id` INT NOT NULL AUTO_INCREMENT,
  `p_playlist_id` INT NOT NULL,
  `c_cancion_id` INT NOT NULL,
  `fecha_cancion_add` INT NOT NULL,
  `add_por_id` INT NOT NULL,
  PRIMARY KEY (`add_cancion_id`),
  UNIQUE INDEX `add_cancion_id_UNIQUE` (`add_cancion_id` ASC) VISIBLE,
  INDEX `play_cancion_idx` (`p_playlist_id` ASC) VISIBLE,
  INDEX `cancion_ad_idx` (`c_cancion_id` ASC) VISIBLE,
  CONSTRAINT `play_cancion`
    FOREIGN KEY (`p_playlist_id`)
    REFERENCES `Spotify`.`playlist` (`playlist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cancion_ad`
    FOREIGN KEY (`c_cancion_id`)
    REFERENCES `Spotify`.`cancion` (`cancion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`pago_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`pago_usuario` (
  `usuario_pago_id` INT NOT NULL,
  `fecha_pago` DATETIME NULL,
  `num_factura` INT NULL,
  `total` DECIMAL(5,5) NULL,
  `fk_sub_pago_id` INT NULL,
  PRIMARY KEY (`usuario_pago_id`),
  INDEX `pago_premium_idx` (`fk_sub_pago_id` ASC) VISIBLE,
  CONSTRAINT `pago_premium`
    FOREIGN KEY (`fk_sub_pago_id`)
    REFERENCES `Spotify`.`usuario_premium` (`sub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`paypal` (
  `paypal_id` INT NOT NULL,
  `usuario_nombre` VARCHAR(50) NULL,
  `fk_sub_id` INT NULL,
  PRIMARY KEY (`paypal_id`),
  INDEX `paypal_idx` (`fk_sub_id` ASC) VISIBLE,
  CONSTRAINT `paypal`
    FOREIGN KEY (`fk_sub_id`)
    REFERENCES `Spotify`.`usuario_premium` (`sub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`tarjeta` (
  `tarjeta_id` INT NOT NULL AUTO_INCREMENT,
  `num_tarjeta` INT NULL,
  `fecha_expiracion` DATETIME NULL,
  `CCV` INT NULL,
  `fk_subcripcion_id` INT NULL,
  PRIMARY KEY (`tarjeta_id`),
  UNIQUE INDEX `tarjeta_id_UNIQUE` (`tarjeta_id` ASC) VISIBLE,
  INDEX `tarjeta_usuario_idx` (`fk_subcripcion_id` ASC) VISIBLE,
  CONSTRAINT `tarjeta_usuario`
    FOREIGN KEY (`fk_subcripcion_id`)
    REFERENCES `Spotify`.`usuario_premium` (`sub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`cancion_favorita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`cancion_favorita` (
  `u_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `c_cancion_id` INT NOT NULL,
  PRIMARY KEY (`u_usuario_id`),
  INDEX `cancion_cancion_idx` (`c_cancion_id` ASC) VISIBLE,
  CONSTRAINT `cancion_fav`
    FOREIGN KEY (`u_usuario_id`)
    REFERENCES `Spotify`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cancion_cancion`
    FOREIGN KEY (`c_cancion_id`)
    REFERENCES `Spotify`.`cancion` (`cancion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`album_favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`album_favorito` (
  `u_usuario_id` INT NOT NULL AUTO_INCREMENT,
  `a_album_id` INT NOT NULL,
  PRIMARY KEY (`u_usuario_id`),
  INDEX `album_fav_idx` (`a_album_id` ASC) VISIBLE,
  CONSTRAINT `album_fav`
    FOREIGN KEY (`a_album_id`)
    REFERENCES `Spotify`.`album` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
