-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 17:54:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cul d'Ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cul d'Ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cul d'Ampolla` DEFAULT CHARACTER SET utf8 ;
USE `Cul d'Ampolla` ;

-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`Clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo_postal` TINYINT NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cliente_recomendado_id` INT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_clientes_UNIQUE` (`id_clientes` ASC) VISIBLE,
  INDEX `1_idx` (`cliente_recomendado_id` ASC) VISIBLE,
  CONSTRAINT `1`
    FOREIGN KEY (`cliente_recomendado_id`)
    REFERENCES `Cul d'Ampolla`.`Clientes` (`id_clientes`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`Color` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_color`),
  UNIQUE INDEX `id_color_UNIQUE` (`id_color` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`Proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `piso` TINYINT(5) NULL DEFAULT NULL,
  `puerta` TINYINT(5) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigo_postal` TINYINT NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `id_proveedor_UNIQUE` (`id_proveedor` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`Montura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`Montura` (
  `id_montura` INT NOT NULL AUTO_INCREMENT,
  `tipo_montura` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_montura`),
  UNIQUE INDEX `id_montura_UNIQUE` (`id_montura` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`Gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`Gafas` (
  `id_gafas` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacion_izquierda` DECIMAL(2,2) NOT NULL,
  `graduacion_derecha` DECIMAL(2,2) NOT NULL,
  `montura_id` INT NOT NULL,
  `color_montura_id` INT NOT NULL,
  `color_cristal_izquierdo_id` INT NOT NULL,
  `color_cristal_derecho_id` INT NOT NULL,
  `precio` DECIMAL(5,5) NOT NULL,
  `proveedor_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_gafas`),
  UNIQUE INDEX `id_gafas_UNIQUE` (`id_gafas` ASC) VISIBLE,
  INDEX `montura` (`montura_id` ASC) VISIBLE,
  INDEX `color_montura` (`color_montura_id` ASC) VISIBLE,
  INDEX `color_cristal_iz` (`color_cristal_izquierdo_id` ASC) VISIBLE,
  INDEX `color_cristal_dch` (`color_cristal_derecho_id` ASC) VISIBLE,
  INDEX `proovedor` (`proveedor_id` ASC) VISIBLE,
  INDEX `3_idx` (`color_montura_id` ASC, `color_cristal_izquierdo_id` ASC, `color_cristal_derecho_id` ASC) VISIBLE,
  CONSTRAINT `2`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `Cul d'Ampolla`.`Proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `3`
    FOREIGN KEY (`color_montura_id` , `color_cristal_izquierdo_id` , `color_cristal_derecho_id`)
    REFERENCES `Cul d'Ampolla`.`Color` (`id_color` , `id_color` , `id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `4`
    FOREIGN KEY (`montura_id`)
    REFERENCES `Cul d'Ampolla`.`Montura` (`id_montura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`Vendedor` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre_vendedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`Venta` (
  `vendedor_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `gafas_id` INT NOT NULL,
  `fecha_venta` DATE NOT NULL,
  INDEX `vendedor` (`vendedor_id` ASC) VISIBLE,
  INDEX `cliente` (`cliente_id` ASC) VISIBLE,
  INDEX `gafas` (`gafas_id` ASC) VISIBLE,
  CONSTRAINT `1`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `Cul d'Ampolla`.`Vendedor` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `2`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Cul d'Ampolla`.`Clientes` (`id_clientes`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `3`
    FOREIGN KEY (`gafas_id`)
    REFERENCES `Cul d'Ampolla`.`Gafas` (`id_gafas`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
